-- AlterTable
ALTER TABLE "studentFields" ALTER COLUMN "status" SET DEFAULT E'ACTIVE',
ALTER COLUMN "grade" SET DEFAULT 1,
ALTER COLUMN "gno" DROP NOT NULL,
ALTER COLUMN "gno" SET DEFAULT 0.00;

-- AlterTable
ALTER TABLE "teacherFields" ALTER COLUMN "website" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "email" SET DATA TYPE VARCHAR(100);
