-- CreateEnum
CREATE TYPE "STUDENTCLASSES_RESULT" AS ENUM ('PASSED', 'FAILED', 'NORESULT');

-- AlterTable
ALTER TABLE "classes" ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "status" SET DEFAULT E'CLOSED';

-- AlterTable
ALTER TABLE "studentClasses" ADD COLUMN     "result" "STUDENTCLASSES_RESULT" DEFAULT E'NORESULT',
ADD COLUMN     "average" DECIMAL(65,30) DEFAULT 0.00,
ADD COLUMN     "letterScore" DECIMAL(65,30) DEFAULT 0.00;
